### PR TITLE
Create running.md

### PR DESCRIPTION
**Pull request by StphnW**

### CODE REVIEW

**Review by alannapowell — APPROVED** [review]
Looks Great!!

**Review by KayTan4 — APPROVED** [review]
Looks good!

**Review by alannapowell — CHANGES_REQUESTED** [review]
Change 'jam' to 'jelly'!

**Review by KayTan4 — APPROVED** [review]

**Comment by KayTan4** [comment]
So I guess the approving review doesn't work because I don't have write access?

**Comment by StphnW** [comment]
@KayTan4  I think you are right!  I "approved" the other ones, but it doesn't seem that I have the ability to write .

**Comment by StphnW** [comment]
Here is my LinkedIn:  https://www.linkedin.com/in/stephanie-wong-0b729524/!

**Review by AnnuJoshi — APPROVED** [review]
Love it! Thanks.

**Pull request merged**
