### PR TITLE
Create swimming.md

### PR DESCRIPTION
**Pull request by alannapowell**

### CODE REVIEW

**Review by KayTan4 — APPROVED** [review]
I APPROVE OF THIS SPORT ;)

**Review by StphnW — APPROVED** [review]
Looks great! Rafting is very fun!

**Comment by KayTan4** [comment]
Feel free to connect with me on LinkedIn! https://www.linkedin.com/in/kaylan-tanuku/

**Review by AnnuJoshi — APPROVED** [review]
Cool! Approved!

**Pull request merged**
